<?php 
/**
 * ZF2 Buch Kapitel 17
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * About us view script
 * 
 * @package    Application
 */

$this->headTitle('Impressum');
$this->pageTitle('Impressum und rechtliche Hinweise');
?>
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.</p>
<p>
<strong>Luigis Pizza-Service</strong><br />
Musterstraße 123<br />
12345 Musterhausen<br />
Tel: 0123 / 456789<br />
Fax: 0123 / 456780<br />
</p>
<p>
<strong>Vertretungsberechtigter Geschäftsführer</strong><br />
Luigi Bartoli<br />
</p>
<p>
<strong>Registergericht</strong><br />
Spagettigericht Musterhausen<br />
</p>
<p>
<strong>Registernummer</strong><br />
ABC 1234 MH<br />
</p>
<p>
<strong>Inhaltlich Verantwortlicher gemäß § 10 Absatz 3 MDStV</strong><br />
Luigi Bartoli<br />
</p>
<p>
<strong>Fotonachweis</strong><br />
Das auf dieser Website verwendete Pizzafoto stammt von der Seite 
<a href="http://pdphoto.org/PictureDetail.php?mat=&pg=6660" target="_blank">pdphoto.org</a>.
</p>
