<?php 
/**
 * ZF2 Buch Kapitel 17
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Team view script
 * 
 * @package    Application
 */

$this->headTitle('Ihr Team');
$this->pageTitle('Ihr Team ist immer für Sie da');
?>
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.</p>
<table class="table-images">
	<tbody>
		<tr>
			<td>
			<p style="text-align: center;"><img alt="Luigi" class="thumbnail span2" src="/img/team/bob.jpg" /></p>

			<p style="text-align: center;">Luigi Bartoli<br />
			Chef</p>
			</td>
			<td>
			<p style="text-align: center;"><img alt="Francesca" class="thumbnail span2" src="/img/team/francesca.png" /></p>

			<p style="text-align: center;">Francesca Bartoli<br />
			Service</p>
			</td>
			<td>
			<p style="text-align: center;"><img alt="Alessandro" class="thumbnail span2" src="/img/team/hubert.jpg" /></p>

			<p style="text-align: center;">Alessandro Altobelli<br />
			Koch</p>
			</td>
			<td>
			<p style="text-align: center;"><img alt="Valentina" class="thumbnail span2" src="/img/team/valentina.png" /></p>

			<p style="text-align: center;">Valentina Rossi<br />
			K&ouml;chin</p>
			</td>
		</tr>
	</tbody>
</table>
<img src="/img/luigis-pizza-logo.gif" alt="Luigis Pizza-Service" /><br />
