<?php
/**
 * ZF2 Buch Kapitel 17
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    User
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * User login widget view script
 * 
 * @package    User
 */

// prepare form
$actionUrl = $this->url('user', array('action' => 'login'));
?>
<div class="well">
<h4 class="pull-center">Je bent niet ingelogd</h4>
<?php echo $this->showForm($this->form, $actionUrl, 'form-vertical'); ?>
</div>